version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: elmehdir/mern-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=elmehdi
      - MONGO_URI=mongodb://mongodb:27017/zxc
    command: sh -c "npm run data:import && npm run server"

  frontend:
    image: elmehdir/mern-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
